

import 'package:get/get.dart';

class MyLocal implements Translations{
  @override
  // TODO: implement keys
  Map<String, Map<String, String>>

  get keys =>
      {
        "ar":{


          "firstName":"الاسم الاول ",
          "lastName":"الاسم الاخير ",
          "email":"البريد الإلكتروني ",

          "privacyPolicy":"سياسة الخصوصية",

          "privacyP":''' Privacy Policy
This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. 
Interpretation and Definitions
Interpretation
The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
Definitions
For the purposes of this Privacy Policy:
	•	Account means a unique account created for You to access our Service or parts of our Service.
	•	Affiliate means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.
	•	Application refers to LETS RALLY, the software program provided by the Company.
	•	Company (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to LETS RALLY.
	•	Country refers to: United Arab Emirates
	•	Device means any device that can access the Service such as a computer, a cellphone or a digital tablet.
	•	Personal Data is any information that relates to an identified or identifiable individual.
	•	Service refers to the Application.
	•	Service Provider means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.
	•	Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).
	•	You means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.
Collecting and Using Your Personal Data
Types of Data Collected
Personal Data
While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
	•	Email address
	•	First name and last name
	•	Phone number
	•	Address, State, Province, ZIP/Postal code, City
	•	Usage Data
Usage Data
Usage Data is collected automatically when using the Service.
Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.
We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.
Information Collected while Using the Application
While using Our Application, in order to provide features of Our Application, We may collect, with Your prior permission:
	•	Information regarding your location
We use this information to provide features of Our Service, to improve and customize Our Service. The information may be uploaded to the Company's servers and/or a Service Provider's server or it may be simply stored on Your device.
You can enable or disable access to this information at any time, through Your Device settings.
Use of Your Personal Data
The Company may use Personal Data for the following purposes:
	•	To provide and maintain our Service, including to monitor the usage of our Service.
	•	To manage Your Account: to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.
	•	For the performance of a contract: the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.
	•	To contact You: To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application's push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.
	•	To provide You with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information.
	•	To manage Your requests: To attend and manage Your requests to Us.
	•	For business transfers: We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by Us about our Service users is among the assets transferred.
	•	For other purposes: We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience.
We may share Your personal information in the following situations:
	•	With Service Providers: We may share Your personal information with Service Providers to monitor and analyze the use of our Service, to contact You.
	•	For business transfers: We may share or transfer Your personal information in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of Our business to another company.
	•	With Affiliates: We may share Your information with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy. Affiliates include Our parent company and any other subsidiaries, joint venture partners or other companies that We control or that are under common control with Us.
	•	With business partners: We may share Your information with Our business partners to offer You certain products, services or promotions.
	•	With other users: when You share personal information or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside.
	•	With Your consent: We may disclose Your personal information for any other purpose with Your consent.
Retention of Your Personal Data
The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.
The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer time periods.
Transfer of Your Personal Data
Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.
Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.
The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.
Delete Your Personal Data
You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You.
Our Service may give You the ability to delete certain information about You from within the Service.
You may update, amend, or delete Your information at any time by signing in to Your Account, if you have one, and visiting the account settings section that allows you to manage Your personal information. You may also contact Us to request access to, correct, or delete any personal information that You have provided to Us.
Please note, however, that We may need to retain certain information when we have a legal obligation or lawful basis to do so.
Disclosure of Your Personal Data
Business Transactions
If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.
Law enforcement
Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).
Other legal requirements
The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:
	•	Comply with a legal obligation
	•	Protect and defend the rights or property of the Company
	•	Prevent or investigate possible wrongdoing in connection with the Service
	•	Protect the personal safety of Users of the Service or the public
	•	Protect against legal liability
Security of Your Personal Data
The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.
Children's Privacy
Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.
If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent's consent before We collect and use that information.
Links to Other Websites
Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.
We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.
Changes to this Privacy Policy
We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.
We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the "Last updated" date at the top of this Privacy Policy.
You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.
Contact Us
If you have any questions about this Privacy Policy, You can contact us:
	•	By email: lets.rally2023@gmail.com
  ''',
          "wrongPass":"كلمة المرور خاطئة ",
          "wrongMail":"البريد الالكتروني خاطئ",

          "reg":"قم بالتسجيل الان ",
          "reg2":"قم باضافة بياناتك الان ",
          "subject":" العنوان  ",
          "msg":" الرسالة   ",
          "sign":"قم بتسجيل الدخول من خلال البريد الإلكتروني و كلمة المرور ",

          "home":" الرئيسية",
          "services":"الخدمات",
           "profile":"الملف الشخصي",
          'send':"ارسال",
          "sendDone":"تم الارسال",
            "appName":"Let's Rally",
             "enterAcademyName":"ادخل اسم الأكاديمية ",
             "academies":"الأكاديميات ",
             "allAcademy":"جميع الأكاديميات ",
             "searchWith":"تصنيف",
             "gender":"النوع",
             "place":"المكان",
             "activity":"النشاط",
              "male":"ذكر",
               "female":"أنثى",
             "both":"كلاهما",
            'next':'التالي',
          'login':"تسجيل دخول ",
          'sureToDelete':"هل تريد حذف حسابك الآن ؟ ",
          "yes":"نعم",
          "no":"لا",
          "forgot2":"الرجاء إدخال بريدك الإلكتروني وسنرسل لك رابطًا للعودة إلى حسابك",
          "reg":"اشتراك ",
  "soon":"متاح قريبًا",

          "suggest":"تحتاج لمساعدة ؟ ",

          "suggest2":"املأ النموذج أدناه وسنتواصل معك قريبًا",

          "changeLang":"تغيير اللغة ",
  "name":"ادخل اسمك ",
  "name2":"الاسم ",
  "phone":"ادخل رقم هاتفك ",
  "phone2":"رفم الهاتف ",


          "enterValidData":"ادخل البيانات بشكل صحيح ",
          "returnHome":"عودة لللرئيسية",

          "school":"المدارس",
           "nurse":"الحضانات",
          "aca":"الأكاديميات ",

          "account":"حسابي",
          "myReg":"جميع الاشتراكات ",
          "lang":"اللغة ",
          "logout":"تسجيل خروج ",
          "noData":"لا توجد بيانات ",

          "contact":"تواصل معنا ",
          "about":"من نحن ",
          "error":"تاكد من ادخال البيانات بشكل صحيح",
          "privacy":"سياسة الخصوصية",
          "terms":"الأحكام و الشروط ",

  "aboutTxt":"""     منذ عام 2021، كنا في مهمة لتسهيل على الآباء العثور على الأنشطة والرياضة لأطفالهم. هدفنا هو توفير منصة سهلة الاستخدام تربط الآباء بالشركات والمؤسسات التي تقدم الأنشطة والبرامج التي سيحبها أطفالهم. وفي المرحلة الثانية من إطلاقنا، سنتعاون مع المدارس ودور الحضانة لتوفير طريقة أسهل للآباء للعثور على البرامج والأنشطة التي يحتاجها أطفال
تم إنشاء تطبيق LETS RALLY من قبل الآباء الذين كانوا يبحثون عن طريقة أسهل للعثور على الأنشطة والرياضة لأطفالهم. يتضمن التطبيق مجموعة واسعة من الأنشطة والرياضات، حتى يتمكن الآباء من العثور بسهولة على ما يبحثون عنه. بالإضافة إلى ذلك، سيكون التطبيق متاحًا للمدارس ودور الحضانة في المستقبل، حتى يتمكن أولياء الأمور من العثور بسهولة على أنشطة لأطفالهم.""",



          "termsTxt":"""Terms and Conditions
Please read these terms and conditions carefully before using our service.
Interpretation and Definitions
Interpretation
The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
Definitions
For the purposes of these Terms and Conditions:
Application means the software program provided by the Company downloaded by You on any electronic device, named LETS RALLY.
Application Store means the digital distribution service operated and developed by Apple Inc. (Apple App Store) or Google Inc. (Google Play Store) in which the Application has been downloaded.
Country refers to: United Arab Emirates
Company (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to LETS RALLY.
Device means any device that can access the Service such as a computer, a cellphone or a digital tablet.
Service refers to the Application.
Terms and Conditions (also referred as "Terms") mean these Terms and Conditions that form the entire agreement between You and the Company regarding the use of the Service. This Terms and Conditions agreement has been created with the help of the TermsFeed Terms and Conditions Generator.
Third-party Social Media Service means any services or content (including data, information, products or services) provided by a third-party that may be displayed, included or made available by the Service.
You means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.
Acknowledgment
These are the Terms and Conditions governing the use of this Service and the agreement that operates between You and the Company. These Terms and Conditions set out the rights and obligations of all users regarding the use of the Service.
Your access to and use of the Service is conditioned on Your acceptance of and compliance with these Terms and Conditions. These Terms and Conditions apply to all visitors, users and others who access or use the Service.
By accessing or using the Service You agree to be bound by these Terms and Conditions. If You disagree with any part of these Terms and Conditions then You may not access the Service.
Your access to and use of the Service is also conditioned on Your acceptance of and compliance with the Privacy Policy of the Company. Our Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your personal information when You use the Application or the Website and tells You about Your privacy rights and how the law protects You. Please read Our Privacy Policy carefully before using Our Service.
Links to Other Websites
Our Service may contain links to third-party web sites or services that are not owned or controlled by the Company.
The Company has no control over, and assumes no responsibility for, the content, privacy policies, or practices of any third party web sites or services. You further acknowledge and agree that the Company shall not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with the use of or reliance on any such content, goods or services available on or through any such web sites or services.
We strongly advise You to read the terms and conditions and privacy policies of any third-party web sites or services that You visit.
Termination
We may terminate or suspend Your access immediately, without prior notice or liability, for any reason whatsoever, including without limitation if You breach these Terms and Conditions.
Upon termination, Your right to use the Service will cease immediately.
"AS IS" and "AS AVAILABLE" Disclaimer
The Service is provided to You "AS IS" and "AS AVAILABLE" and with all faults and defects without warranty of any kind. To the maximum extent permitted under applicable law, the Company, on its own behalf and on behalf of its Affiliates and its and their respective licensors and service providers, expressly disclaims all warranties, whether express, implied, statutory or otherwise, with respect to the Service, including all implied warranties of merchantability, fitness for a particular purpose, title and non-infringement, and warranties that may arise out of course of dealing, course of performance, usage or trade practice. Without limitation to the foregoing, the Company provides no warranty or undertaking, and makes no representation of any kind that the Service will meet Your requirements, achieve any intended results, be compatible or work with any other software, applications, systems or services, operate without interruption, meet any performance or reliability standards or be error free or that any errors or defects can or will be corrected.
Without limiting the foregoing, neither the Company nor any of the company's provider makes any representation or warranty of any kind, express or implied: (i) as to the operation or availability of the Service, or the information, content, and materials or products included thereon; (ii) that the Service will be uninterrupted or error-free; (iii) as to the accuracy, reliability, or currency of any information or content provided through the Service; or (iv) that the Service, its servers, the content, or e-mails sent from or on behalf of the Company are free of viruses, scripts, trojan horses, worms, malware, timebombs or other harmful components.
Some jurisdictions do not allow the exclusion of certain types of warranties or limitations on applicable statutory rights of a consumer, so some or all of the above exclusions and limitations may not apply to You. But in such a case the exclusions and limitations set forth in this section shall be applied to the greatest extent enforceable under applicable law.
Governing Law
The laws of the Country, excluding its conflicts of law rules, shall govern this Terms and Your use of the Service. Your use of the Application may also be subject to other local, state, national, or international laws.
Disputes Resolution
If You have any concern or dispute about the Service, You agree to first try to resolve the dispute informally by contacting the Company.
Severability and Waiver
Severability
If any provision of these Terms is held to be unenforceable or invalid, such provision will be changed and interpreted to accomplish the objectives of such provision to the greatest extent possible under applicable law and the remaining provisions will continue in full force and effect.
Waiver
Except as provided herein, the failure to exercise a right or to require performance of an obligation under these Terms shall not effect a party's ability to exercise such right or require such performance at any time thereafter nor shall the waiver of a breach constitute a waiver of any subsequent breach.
Changes to These Terms and Conditions
We reserve the right, at Our sole discretion, to modify or replace these Terms at any time. If a revision is material We will make reasonable efforts to provide at least 30 days' notice prior to any new terms taking effect. What constitutes a material change will be determined at Our sole discretion.
By continuing to access or use Our Service after those revisions become effective, You agree to be bound by the revised terms. If You do not agree to the new terms, in whole or in part, please stop using the website and the Service.
Contact Us
If you have any questions about these Terms and Conditions, You can contact us:
By email: lets.rally2023@gmail.com

          
          
          """,

          "fieldEmpty": "لا تترك الحقل فارغاً",
          "newPass": 'كلمة مرور جديدة',
          "confirmPass": 'تاكيد كلمة المرور ',
          "username": "اسم المستخدم",
          "check": "هل تريد تفقد التطبيق؟",
          "visit": "قم بزيارتنا!",
          "dontHaveAccount": "ليس لديك حساب؟",
          "signup": "تسجيل حساب",
          "reset": "إعادة تعيين",
          "loginfirst": "قم بتسجيل الدخول أولاً",
          "forgotPassword": "نسيت كلمة السر؟",
          "sendMail": "استعادة كلمة المرور",
          "checkMail": "تفقد بريدك الإلكتروني",
          "forgetPassword":"نسيت كلمة المرور ",
          "password":"كلمة المرور ",
          "haveAccount":"لدي حساب بالفعل ",
          "info":"المعلومات الشخصية",

          "newPhone":"رقم الهاتف الجديد ",
          "changePhone":"تغيير رقم الهاتف ",
          "saveChanges":"حفظ التغييرات ",
          "changePass":"تغيير كلمة المرور ",
          "passwordUpdate":"تم تغيير كلمة المرور بنجاح "

        },
        "en":{
          "home":"Home",
          "newPhone":"new phone number ",
  "haveAccount":"already have account ? ",
          "contact":"Contact us",
          "services":"Services",
          "profile":"Profile",
          "reg":"Register Your Account ",
          "reg2":"Complete your details",

          "appName":"Let's Rally",
          "enterAcademyName":"Enter academy name  ",
          "academies":"Academies",
  "passwordUpdate":" Password Updated Successfully  ",
          "allAcademy":"See All ",
          "searchWith":"Filter ",
          "changeLang":"Change Language  ",
          "yes":"Yes",
          "no":"No",
          "gender":"Gender ",
          "place":"Location",
          "sendDone":"Your Msg Sent ",
          "wrongPass":"You Entered Wrong Password ",
          "activity":"Activity",
  "forgetPassword":"Forgot Password",

          "male":"Male",
          "female":"Female",
          "noData":"No Data  ",
          "both":"Both",
          'next':'Next',
          'sureToDelete':"Are you sure to delete your account",
          "deleteAccount":"Delete Account",
          "reg":"Register",
          "name":"Enter Your Full Name",
          "name2":"Name",
          "phone":"Enter Your Phone",
          "phone2":"Phone",
          "enterValidData":"Enter Valid Data ",
          "suggest":"Suggestion Help ?",
          "suggest2":"Fill out the form below and we will be in touch soon",
          "returnHome":"Return Home",
          "school":"School",
          "nurse":"Nursery",
          "aca":"Academy",
          "account":"My Account",
          "myReg":"My Registers",
          "lang":"Language",
          "logout":"Logout",
          "terms":"Terms and Conditions",
          'send':"Send",
          "firstName":"First Name",
          "lastName":"Last Name",
          "error":"Enter Information Successfully ",
          "email":"Email ",
          "subject":" Subject ",
          "msg":" Message   ",
          "wrongMail":"You Entered Wrong Mail ",
          "changePass":"Change Your Password",

          "privacyPolicy":"privacy Policy",

          "privacyP":''' Privacy Policy
This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. 
Interpretation and Definitions
Interpretation
The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
Definitions
For the purposes of this Privacy Policy:
	•	Account means a unique account created for You to access our Service or parts of our Service.
	•	Affiliate means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.
	•	Application refers to LETS RALLY, the software program provided by the Company.
	•	Company (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to LETS RALLY.
	•	Country refers to: United Arab Emirates
	•	Device means any device that can access the Service such as a computer, a cellphone or a digital tablet.
	•	Personal Data is any information that relates to an identified or identifiable individual.
	•	Service refers to the Application.
	•	Service Provider means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.
	•	Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).
	•	You means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.
Collecting and Using Your Personal Data
Types of Data Collected
Personal Data
While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
	•	Email address
	•	First name and last name
	•	Phone number
	•	Address, State, Province, ZIP/Postal code, City
	•	Usage Data
Usage Data
Usage Data is collected automatically when using the Service.
Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.
We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.
Information Collected while Using the Application
While using Our Application, in order to provide features of Our Application, We may collect, with Your prior permission:
	•	Information regarding your location
We use this information to provide features of Our Service, to improve and customize Our Service. The information may be uploaded to the Company's servers and/or a Service Provider's server or it may be simply stored on Your device.
You can enable or disable access to this information at any time, through Your Device settings.
Use of Your Personal Data
The Company may use Personal Data for the following purposes:
	•	To provide and maintain our Service, including to monitor the usage of our Service.
	•	To manage Your Account: to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.
	•	For the performance of a contract: the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.
	•	To contact You: To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application's push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.
	•	To provide You with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information.
	•	To manage Your requests: To attend and manage Your requests to Us.
	•	For business transfers: We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by Us about our Service users is among the assets transferred.
	•	For other purposes: We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience.
We may share Your personal information in the following situations:
	•	With Service Providers: We may share Your personal information with Service Providers to monitor and analyze the use of our Service, to contact You.
	•	For business transfers: We may share or transfer Your personal information in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of Our business to another company.
	•	With Affiliates: We may share Your information with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy. Affiliates include Our parent company and any other subsidiaries, joint venture partners or other companies that We control or that are under common control with Us.
	•	With business partners: We may share Your information with Our business partners to offer You certain products, services or promotions.
	•	With other users: when You share personal information or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside.
	•	With Your consent: We may disclose Your personal information for any other purpose with Your consent.
Retention of Your Personal Data
The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.
The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer time periods.
Transfer of Your Personal Data
Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.
Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.
The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.
Delete Your Personal Data
You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You.
Our Service may give You the ability to delete certain information about You from within the Service.
You may update, amend, or delete Your information at any time by signing in to Your Account, if you have one, and visiting the account settings section that allows you to manage Your personal information. You may also contact Us to request access to, correct, or delete any personal information that You have provided to Us.
Please note, however, that We may need to retain certain information when we have a legal obligation or lawful basis to do so.
Disclosure of Your Personal Data
Business Transactions
If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.
Law enforcement
Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).
Other legal requirements
The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:
	•	Comply with a legal obligation
	•	Protect and defend the rights or property of the Company
	•	Prevent or investigate possible wrongdoing in connection with the Service
	•	Protect the personal safety of Users of the Service or the public
	•	Protect against legal liability
Security of Your Personal Data
The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.
Children's Privacy
Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.
If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent's consent before We collect and use that information.
Links to Other Websites
Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.
We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.
Changes to this Privacy Policy
We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.
We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the "Last updated" date at the top of this Privacy Policy.
You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.
Contact Us
If you have any questions about this Privacy Policy, You can contact us:
	•	By email: lets.rally2023@gmail.com
  ''',
          "aboutTxt":'''Since 2021, we have been on a mission to make it easier for parents to find activities and sports for their children. Our goal is to provide an easy-to-use platform that connects parents with the businesses and organizations that offer the activities and programs that their kids will love. In the second phase of our launch, we will be partnering with schools and nurseries to provide an even easier way for parents to find the programs and activities that their children need.The LETS RALLY APP was created by a parents who were looking for an easier way to find activities and sports for their children. The app includes a wide variety of activities and sports, so that parents can easily find what they are looking for. In addition, the app will be available to schools and nurseries in the future, so that parents can easily find activities for their children.
          ''',


          "termsTxt":"""Terms and Conditions
Please read these terms and conditions carefully before using our service.
Interpretation and Definitions
Interpretation
The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
Definitions
For the purposes of these Terms and Conditions:
Application means the software program provided by the Company downloaded by You on any electronic device, named LETS RALLY.
Application Store means the digital distribution service operated and developed by Apple Inc. (Apple App Store) or Google Inc. (Google Play Store) in which the Application has been downloaded.
Country refers to: United Arab Emirates
Company (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to LETS RALLY.
Device means any device that can access the Service such as a computer, a cellphone or a digital tablet.
Service refers to the Application.
Terms and Conditions (also referred as "Terms") mean these Terms and Conditions that form the entire agreement between You and the Company regarding the use of the Service. This Terms and Conditions agreement has been created with the help of the TermsFeed Terms and Conditions Generator.
Third-party Social Media Service means any services or content (including data, information, products or services) provided by a third-party that may be displayed, included or made available by the Service.
You means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.
Acknowledgment
These are the Terms and Conditions governing the use of this Service and the agreement that operates between You and the Company. These Terms and Conditions set out the rights and obligations of all users regarding the use of the Service.
Your access to and use of the Service is conditioned on Your acceptance of and compliance with these Terms and Conditions. These Terms and Conditions apply to all visitors, users and others who access or use the Service.
By accessing or using the Service You agree to be bound by these Terms and Conditions. If You disagree with any part of these Terms and Conditions then You may not access the Service.
Your access to and use of the Service is also conditioned on Your acceptance of and compliance with the Privacy Policy of the Company. Our Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your personal information when You use the Application or the Website and tells You about Your privacy rights and how the law protects You. Please read Our Privacy Policy carefully before using Our Service.
Links to Other Websites
Our Service may contain links to third-party web sites or services that are not owned or controlled by the Company.
The Company has no control over, and assumes no responsibility for, the content, privacy policies, or practices of any third party web sites or services. You further acknowledge and agree that the Company shall not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with the use of or reliance on any such content, goods or services available on or through any such web sites or services.
We strongly advise You to read the terms and conditions and privacy policies of any third-party web sites or services that You visit.
Termination
We may terminate or suspend Your access immediately, without prior notice or liability, for any reason whatsoever, including without limitation if You breach these Terms and Conditions.
Upon termination, Your right to use the Service will cease immediately.
"AS IS" and "AS AVAILABLE" Disclaimer
The Service is provided to You "AS IS" and "AS AVAILABLE" and with all faults and defects without warranty of any kind. To the maximum extent permitted under applicable law, the Company, on its own behalf and on behalf of its Affiliates and its and their respective licensors and service providers, expressly disclaims all warranties, whether express, implied, statutory or otherwise, with respect to the Service, including all implied warranties of merchantability, fitness for a particular purpose, title and non-infringement, and warranties that may arise out of course of dealing, course of performance, usage or trade practice. Without limitation to the foregoing, the Company provides no warranty or undertaking, and makes no representation of any kind that the Service will meet Your requirements, achieve any intended results, be compatible or work with any other software, applications, systems or services, operate without interruption, meet any performance or reliability standards or be error free or that any errors or defects can or will be corrected.
Without limiting the foregoing, neither the Company nor any of the company's provider makes any representation or warranty of any kind, express or implied: (i) as to the operation or availability of the Service, or the information, content, and materials or products included thereon; (ii) that the Service will be uninterrupted or error-free; (iii) as to the accuracy, reliability, or currency of any information or content provided through the Service; or (iv) that the Service, its servers, the content, or e-mails sent from or on behalf of the Company are free of viruses, scripts, trojan horses, worms, malware, timebombs or other harmful components.
Some jurisdictions do not allow the exclusion of certain types of warranties or limitations on applicable statutory rights of a consumer, so some or all of the above exclusions and limitations may not apply to You. But in such a case the exclusions and limitations set forth in this section shall be applied to the greatest extent enforceable under applicable law.
Governing Law
The laws of the Country, excluding its conflicts of law rules, shall govern this Terms and Your use of the Service. Your use of the Application may also be subject to other local, state, national, or international laws.
Disputes Resolution
If You have any concern or dispute about the Service, You agree to first try to resolve the dispute informally by contacting the Company.
Severability and Waiver
Severability
If any provision of these Terms is held to be unenforceable or invalid, such provision will be changed and interpreted to accomplish the objectives of such provision to the greatest extent possible under applicable law and the remaining provisions will continue in full force and effect.
Waiver
Except as provided herein, the failure to exercise a right or to require performance of an obligation under these Terms shall not effect a party's ability to exercise such right or require such performance at any time thereafter nor shall the waiver of a breach constitute a waiver of any subsequent breach.
Changes to These Terms and Conditions
We reserve the right, at Our sole discretion, to modify or replace these Terms at any time. If a revision is material We will make reasonable efforts to provide at least 30 days' notice prior to any new terms taking effect. What constitutes a material change will be determined at Our sole discretion.
By continuing to access or use Our Service after those revisions become effective, You agree to be bound by the revised terms. If You do not agree to the new terms, in whole or in part, please stop using the website and the Service.
Contact Us
If you have any questions about these Terms and Conditions, You can contact us:
By email: lets.rally2023@gmail.com

          
          
          """,


          "fieldEmpty": "Field Empty ً",
          "about":"About us",
          "newPass": 'New Password',
          "confirmPass": 'Confirm Password ',
          "username": "User Name",
          "check": "Check App",
          "visit": "Visit Us ",
          "dontHaveAccount": "Don't Have Account ? ",
          "signup": "Signup ",
          "reset": "Reset ",
          "loginfirst": "Must Login First ً",
          "forgotPassword": "Forgot Password",
          "forgot2": "Please enter your email and we will send you a link to return to your account",
          "sendMail": "Reset Password",
          "checkMail": "Check Your Mail ",
           "password":"Password",
          "info":"Personal Information",
          'login':"Login ",
          "sign":"Sign in with your email and password",
          "changePhone":"Change Phone ",
          "saveChanges":"Save Changes ",
        //  "changePass":"Change Password  ",
          "soon":"Available Soon"


        }
      };
}